# Generated by Django 6.0.6 on 2026-06-27 02:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Maladie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Code court, ex. palu, chol, covid.', max_length=10, unique=True)),
                ('nom', models.CharField(max_length=60)),
                ('nom_en', models.CharField(blank=True, max_length=60, verbose_name='nom (anglais)')),
                ('couleur', models.CharField(default='#1763C6', help_text="Couleur d'accent (hex) utilisée dans les graphiques.", max_length=7)),
                ('seuil_incidence', models.FloatField(help_text="Seuil d'incidence pour 100 000 habitants au-delà duquel une alerte est déclenchée.", verbose_name='seuil épidémique')),
                ('cfr', models.FloatField(default=0, help_text='Case Fatality Rate : pourcentage de cas mortels.', verbose_name='létalité (%)')),
                ('rt', models.FloatField(default=1.0, verbose_name='taux de reproduction (Rt)')),
            ],
            options={
                'verbose_name': 'Maladie',
                'verbose_name_plural': 'Maladies',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Code court de la région, ex. DK pour Dakar.', max_length=2, unique=True)),
                ('nom', models.CharField(max_length=80)),
                ('nom_court', models.CharField(blank=True, max_length=20)),
                ('population', models.PositiveIntegerField(help_text='Population totale de la région.')),
            ],
            options={
                'verbose_name': 'Région',
                'verbose_name_plural': 'Régions',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=80)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='sanitrax.region')),
            ],
            options={
                'verbose_name': 'District sanitaire',
                'verbose_name_plural': 'Districts sanitaires',
                'ordering': ['region', 'nom'],
                'unique_together': {('region', 'nom')},
            },
        ),
        migrations.CreateModel(
            name='DeclarationCas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sexe', models.CharField(blank=True, choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1)),
                ('age', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='âge')),
                ('nombre_cas', models.PositiveIntegerField(default=1, verbose_name='nombre de cas')),
                ('date_notification', models.DateField()),
                ('statut', models.CharField(choices=[('suspecte', 'Suspecté'), ('probable', 'Probable'), ('confirme', 'Confirmé')], default='suspecte', max_length=10)),
                ('observations', models.TextField(blank=True, verbose_name='observations cliniques')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='declarations', to='sanitrax.district')),
                ('maladie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='declarations', to='sanitrax.maladie')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='declarations', to='sanitrax.region')),
            ],
            options={
                'verbose_name': 'Déclaration de cas',
                'verbose_name_plural': 'Déclarations de cas',
                'ordering': ['-date_notification', '-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Alerte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incidence', models.FloatField(help_text='Incidence observée pour 100 000 hab.')),
                ('seuil', models.FloatField(help_text='Seuil épidémique de la maladie au moment de la détection.')),
                ('ratio', models.FloatField(help_text='incidence / seuil (≥ 1 = dépassement).')),
                ('niveau', models.IntegerField(choices=[(1, 'Modéré'), (2, 'Élevé'), (3, 'Critique')], default=1)),
                ('statut', models.CharField(choices=[('active', 'Active'), ('prise_en_charge', 'Prise en charge'), ('resolue', 'Résolue')], default='active', max_length=20)),
                ('date_detection', models.DateTimeField(auto_now_add=True)),
                ('maladie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertes', to='sanitrax.maladie')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertes', to='sanitrax.region')),
            ],
            options={
                'verbose_name': 'Alerte',
                'verbose_name_plural': 'Alertes',
                'ordering': ['-ratio'],
                'unique_together': {('maladie', 'region')},
            },
        ),
    ]
