# Generated by Django 6.0.6 on 2026-06-27 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanitrax', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='latitude',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='region',
            name='longitude',
            field=models.FloatField(default=0),
        ),
    ]
