# Generated by Django 6.0.6 on 2026-06-28 15:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanitrax', '0002_region_latitude_region_longitude'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='declarationcas',
            name='declare_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='declarations', to=settings.AUTH_USER_MODEL, verbose_name='déclaré par'),
        ),
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Administrateur'), ('agent', 'Agent régional'), ('epi', 'Épidémiologiste'), ('decideur', 'Décideur ministériel')], default='epi', max_length=20)),
                ('region', models.ForeignKey(blank=True, help_text='Région de rattachement (pour les agents régionaux).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agents', to='sanitrax.region')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil utilisateur',
                'verbose_name_plural': 'Profils utilisateurs',
            },
        ),
    ]
