# Generated by Django 6.0.6 on 2026-06-29 05:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanitrax', '0003_declarationcas_declare_par_profil'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='district',
            options={'ordering': ['region', 'nom'], 'verbose_name': 'Département', 'verbose_name_plural': 'Départements'},
        ),
        migrations.AddField(
            model_name='alerte',
            name='declencheur',
            field=models.CharField(choices=[('incidence', "Seuil d'incidence hebdomadaire"), ('cas_24h', 'Seuil de cas en 24h'), ('les_deux', 'Incidence + cas 24h')], default='incidence', help_text="Règle qui a déclenché l'alerte.", max_length=10),
        ),
        migrations.AddField(
            model_name='alerte',
            name='pic_24h',
            field=models.PositiveIntegerField(default=0, help_text='Plus grand nombre de cas notifiés en une journée sur la semaine.', verbose_name='pic de cas en 24h'),
        ),
        migrations.AddField(
            model_name='declarationcas',
            name='gravite',
            field=models.CharField(choices=[('modere', 'Modéré'), ('severe', 'Sévère'), ('critique', 'Critique'), ('deces', 'Décès')], default='modere', max_length=10, verbose_name='gravité'),
        ),
        migrations.AlterField(
            model_name='declarationcas',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='declarations', to='sanitrax.district', verbose_name='département'),
        ),
        migrations.CreateModel(
            name='Commune',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=80)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communes', to='sanitrax.district', verbose_name='département')),
            ],
            options={
                'verbose_name': 'Commune',
                'verbose_name_plural': 'Communes',
                'ordering': ['district', 'nom'],
                'unique_together': {('district', 'nom')},
            },
        ),
        migrations.AddField(
            model_name='declarationcas',
            name='commune',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='declarations', to='sanitrax.commune'),
        ),
        migrations.CreateModel(
            name='Structure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=120)),
                ('type', models.CharField(choices=[('hopital', 'Hôpital'), ('centre', 'Centre de santé'), ('poste', 'Poste de santé')], default='centre', max_length=10)),
                ('commune', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='structures', to='sanitrax.commune')),
            ],
            options={
                'verbose_name': 'Centre de santé',
                'verbose_name_plural': 'Centres de santé',
                'ordering': ['commune', 'nom'],
            },
        ),
        migrations.AddField(
            model_name='declarationcas',
            name='structure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='declarations', to='sanitrax.structure', verbose_name='centre de santé'),
        ),
    ]
