# Generated by Django 6.0.6 on 2026-06-29 05:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanitrax', '0004_alter_district_options_alerte_declencheur_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalConnexion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_saisi', models.CharField(blank=True, max_length=254, verbose_name='e-mail saisi')),
                ('evenement', models.CharField(choices=[('connexion', 'Connexion'), ('deconnexion', 'Déconnexion'), ('echec', 'Échec de connexion')], max_length=12, verbose_name='événement')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='date et heure')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='connexions', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
            ],
            options={
                'verbose_name': 'Journal de connexion',
                'verbose_name_plural': 'Journal des connexions',
                'ordering': ['-date'],
            },
        ),
    ]
