# Generated by Django 6.0.6 on 2026-06-30 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanitrax', '0005_journalconnexion'),
    ]

    operations = [
        migrations.AddField(
            model_name='declarationcas',
            name='evolution',
            field=models.CharField(choices=[('en_cours', 'En cours'), ('gueri', 'Guéri'), ('decede', 'Décédé')], default='en_cours', max_length=10, verbose_name='évolution'),
        ),
        migrations.AlterField(
            model_name='declarationcas',
            name='gravite',
            field=models.CharField(choices=[('modere', 'Modéré'), ('severe', 'Sévère'), ('critique', 'Critique')], default='modere', max_length=10, verbose_name='gravité'),
        ),
    ]
